In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = np.load('Data.npz')

In [3]:
dataset = dataset.f.arr_0

In [4]:
dataset

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
dataset.shape

(1797, 64)

In [6]:
X = dataset.T
X.shape

(64, 1797)

In [7]:
x_bar = np.mean(X, axis = 1)

In [8]:
x_bar.shape

(64,)

In [9]:
(X-x_bar[:,np.newaxis]).shape

(64, 1797)

In [10]:
S = (1/X.shape[1])*np.matmul(X-x_bar[:, np.newaxis], (X-x_bar[:, np.newaxis]).T)

In [11]:
S.shape

(64, 64)

In [12]:
w, v = np.linalg.eig(S)

In [14]:
w

array([1.78907316e+02, 1.63626641e+02, 1.41709536e+02, 1.01044115e+02,
       6.94744827e+01, 5.90756320e+01, 5.18556662e+01, 4.39906130e+01,
       4.02885629e+01, 3.69912020e+01, 2.85031708e+01, 2.73059660e+01,
       2.18893003e+01, 2.13124899e+01, 1.76269077e+01, 1.69374332e+01,
       1.58425689e+01, 1.49961105e+01, 1.22276649e+01, 1.08808010e+01,
       1.06876155e+01, 9.57726524e+00, 9.22126826e+00, 8.68553268e+00,
       8.36095658e+00, 7.16179198e+00, 6.91588809e+00, 6.18950881e+00,
       5.88171633e+00, 5.15299774e+00, 4.48879723e+00, 4.24451468e+00,
       4.04518650e+00, 3.94120891e+00, 3.70440987e+00, 3.52968776e+00,
       3.08285758e+00, 2.73627648e+00, 2.67062197e+00, 2.54029121e+00,
       2.28171700e+00, 1.90618094e+00, 1.81615447e+00, 1.68902395e+00,
       1.40119202e+00, 1.29149979e+00, 1.15828926e+00, 9.30701800e-01,
       6.69477833e-01, 4.85794730e-01, 2.52210004e-01, 9.90976176e-02,
       6.30956535e-02, 6.07039586e-02, 3.96441561e-02, 1.49422438e-02,
      

In [15]:
v

array([[ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.01730947,  0.01010646, -0.01834207, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.22342883,  0.04908492, -0.12647554, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.08941847, -0.17669712, -0.23208416, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.03659771, -0.01945471, -0.16702656, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.0114685 ,  0.00669694, -0.03480438, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
np.linalg.norm(v[:, 63])

In [ ]:
v[:, 60]

In [ ]:
np.matmul(v[:,10].T, v[:, 24])

In [ ]:
m_dim = 10
X_transformed = np.matmul(v[:, :m_dim].T, X)

In [ ]:
X_transformed.shape

In [ ]:
test = X[:,131].reshape(8,8)

In [ ]:
plt.imshow(test)

In [ ]:
a = np.array([1,3,5,7,9,11])
b = np.cumsum(a)

In [ ]:
b

In [ ]:
S

In [ ]:
w

In [ ]:
def PCA(dataset, m_dim):
    """ Implements PCA on the provided dataset.
    
    Arguments:
        
        dataset - shape n*d
        m_dim - number of principal components
        
    Returns:
    
        dataset_pca - shape m*d
        v - the set of orthogonal basis vectors of the target space
    """
    
    # Finding the covariance matrix
    X = dataset.T
    x_bar = np.mean(X, axis = 1)
    S = (1/X.shape[1])*np.matmul(X-x_bar[:, np.newaxis], (X-x_bar[:, np.newaxis]).T)
    
    # Finding eigenvalues and eigenvectors
    
    w, v = np.linalg.eig(S) # w is the array of eigenvalues, and the columns of v are the corresponding eigenvectors
    
    # Transforming the data to a lower dimension space
    
    Z = np.zeros((m_dim, X.shape[1])) # Z contains the coefficients of the Principal Components
    b = np.zeros((m_dim, 1)) # Bias term
    
    for i in range(X.shape[1]):
        Z[:, i] = np.matmul(X[:, i].T, v[:,:m_dim]).T
        
    b = np.matmul(x_bar.T, v[:, m_dim:]).T[:, np.newaxis]
    
    return Z, b, v

In [ ]:
Z, b, v = PCA(dataset, 2)

In [ ]:
Z.shape

In [ ]:
b.shape

In [ ]:
X_tilde = np.zeros_like(X)

In [ ]:
X_tilde.shape

In [ ]:
X_reconstructed = np.zeros_like(X)

In [ ]:
X_reconstructed += np.matmul(v[:, :2], Z)

In [ ]:
X_reconstructed += np.matmul(v[:, 2:], b)

In [ ]:
np.linalg.norm(X-X_reconstructed)

In [ ]:
plt.imshow(X[:, 1700].reshape(8,8))

In [ ]:
plt.imshow(X_reconstructed[:, 1700].reshape(8,8))

In [ ]:
x = X[:, 23]

In [ ]:
x.shape

In [ ]:
x = x[:, np.newaxis]

In [ ]:
x.shape

In [ ]:
R = np.ones((2,3))

In [ ]:
vector = np.array([3,4])
np.linalg.norm(vector)

In [ ]:
np.sum(w[2:])

In [ ]:
Z, b, v = PCA(dataset, 8)

In [ ]:
def Kmeans(dataset, k):
    """" Implements K-Means Clustering on the provided dataset
    
    Arguments:
    
        dataset - shape n*d
        k - number of clusters
        
    Returns:
    
        mean_vectors - shape d*k
        R - responsibilities - shape n*k
    """   
    X = dataset.T
    R = np.zeros((dataset.shape[0], k)) # Rows of R are the responsibility vectors for each datapoint
    mean_vectors = X[:, :k] # Columns are the mean vectors of each cluster
    
    iterations = 20
    
    for i in range(iterations):
        
        for l in range(X.shape[1]):
            x = X[:, l]
            distances = np.array([np.linalg.norm(x-mean_vectors[:,f]) for f in range(k)])
            cluster = np.argmin(distances)
            r = np.zeros((1, k))
            r[0, cluster] = 1
            R[l, :] = r
            
        for l in range(mean_vectors.shape[1]):
            mean_vectors[:, l] = np.matmul(X, R[:, l])/(np.sum(R[:, l]))
            
    return mean_vectors, R

In [ ]:
mean_vectors, R = Kmeans(Z.T, 10)

In [ ]:
R = np.ones((X.shape[1], 10))

In [ ]:
mean_vectors = np.ones((X.shape[0], 10))

In [ ]:
X.shape

In [ ]:
R.shape

In [ ]:
R[:, 4].shape

In [ ]:
R[:, 4][:, np.newaxis].shape

In [ ]:
test = np.matmul(X, R[:, 4])

In [ ]:
test.shape

In [ ]:
test2 = np.sum(R[:, 4])

In [ ]:
test2.shape

In [ ]:
test3 = test/test2

In [ ]:
test3.shape

In [ ]:
mean_vectors[:,4] = test3

In [ ]:
test3.shape

In [ ]:
test = mean_vectors[:,2]
Z8, b8, v8 = PCA(dataset, 8)

In [ ]:
test_reconstructed = np.zeros_like(X[:,1])
test_reconstructed += np.matmul(v[:, :8], test)
test_reconstructed += np.matmul(v[:, 2:], b8)


In [ ]:
test.shape

In [ ]:
Z8, b8, v8 = PCA(dataset, 8)
X_reconstructed_8 = np.zeros_like(X)
X_reconstructed_8 += np.matmul(v8[:, :8], Z8)
X_reconstructed_8 += np.matmul(v8[:, 8:], b8)

In [ ]:
mean_vectors, R = Kmeans(Z8.T, 10)

In [ ]:
R[1]

In [ ]:
R[5]

In [ ]:
R[100]

In [ ]:
R[121]

In [ ]:
R[1000]

In [ ]:
k=10
cluster = 5

In [ ]:
r = np.zeros((1, k))
r[0, cluster] = 1

In [ ]:
r

In [ ]:
k=10
R = np.zeros((dataset.shape[0], k)) # Rows of R are the responsibility vectors for each datapoint
mean_vectors = X[:, :k] # Columns are the mean vectors of each cluster

In [ ]:
x = X[:, 2][:, np.newaxis]

In [ ]:
x.shape

In [ ]:
distances = np.array([np.linalg.norm(x-mean_vectors[:,f]) for f in range(k)])

In [ ]:
distances

In [ ]:
X[:,k-1]

In [ ]:
mean_vectors[:,k-1]

In [ ]:
np.linalg.norm(x-mean_vectors[:,2])

In [ ]:
x = X[:, 2]

In [ ]:
x

In [ ]:
mean_vectors[:,2]

In [ ]:
x-mean_vectors[:,2]

In [ ]:
R[1]

In [ ]:
R[100]

In [ ]:
mean_vectors, R = Kmeans(X.T, 10)

In [ ]:
plt.imshow(mean_vectors[:,3].reshape(8,8))

In [ ]:
for cluster in clusters:
    plt.scatter(cluster[0], cluster[1])
plt.show()